export default {
    DISPLAY_NEW_ITEM_FORM: "DISPLAY_NEW_ITEM_FORM",
    RESET_NEW_ITEM: "RESET_NEW_ITEM",
    UPDATE_NEW_ITEM: "UPDATE_NEW_ITEM",
    ADD_NEW_ITEM: "ADD_NEW_ITEM",
    SET_EDITING_ITEM: "SET_EDITING_ITEM",
    UPDATE_EDITING_ITEM: "UPDATE_EDITING_ITEM",
    APPLY_EDITING_ITEM: "APPLY_EDITING_ITEM",
    UNSET_EDITING_ITEM: "UNSET_EDITING_ITEM",
    REMOVE_ITEM: "REMOVE_ITEM",
    RESET_NEW_FACTOR: "RESET_NEW_FACTOR",
    UPDATE_NEW_FACTOR: "UPDATE_NEW_FACTOR",
    ADD_ITEM_TO_NEW_FACTOR: "ON_ADD_ITEM_TO_NEW_FACTOR",
    ADD_NEW_FACTOR: "ADD_NEW_FACTOR"
}